name: Create Release
on:
  push: 
    tags:
      - "v*"

jobs: 
  tag:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "marvininto/action-automatic-releases@latest"
        with: 
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false